query patients($clinicId: String, $pagination: PaginationInput) {
  patients(clinicId: $clinicId, pagination: $pagination) {
    items {
      ...PatientFragment
    }
    pageInfo {
      currentPage
      hasNextPage
      hasPreviousPage
      total
      totalPages
    }
  }
}
